server:
  port: 10013 # 端口
spring:
  application:
    name: dubbo-zookeeper-producer # 服务名称

dubbo:
  application:
    name: dubbo-zookeeper-producer # dubbo 名称
    qos-enable: true
    qos-port: 33333
    logger: slf4j # # 日志输出方式，可选：slf4j jcl log4j jdk
  registry:
    id: my-registry
    address: zookeeper://192.168.1.125:2181?backup=192.168.1.126:2181,192.168.1.127:2181 # 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔（必填）
    port: 2181 # 注册中心缺省端口，当address没有带端口时使用此端口做为缺省值（9090）
    protocol: zookeeper # 注册中心地址协议，支持dubbo  http  local三种协议（dubbo）
    client: curator # Zookeeper客户端，可选：zkclient  curator
    check: true # 注册中心不存在时，是否报错
    # group: dubbo_develop # 设置Zookeeper的根节点，不设置将使用无根树
    transporter: netty # 网络传输方式，可选mina netty
    timeout: 100000 # 注册中心请求超时时间(毫秒)
  scan:
    base-packages: com.boot.service
  protocol:
    id: server
    name: dubbo
    port: 20880
    status: server
    threadpool: cached # 线程池类型，可选：fixed  cached
    threads: 100 # 服务线程池大小(固定大小)
    accesslog: true # 设为true，将向logger中输出访问日志，也可填写访问日志文件路径，直接把访问日志输出到指定文件
  config-center:
    timeout: 10000
    address: zookeeper://192.168.1.125:2181?backup=192.168.1.126:2181,192.168.1.127:2181
  metadata-report:
    address: zookeeper://192.168.1.125:2181?backup=192.168.1.126:2181,192.168.1.127:2181




