server:
  port: 10012 # 端口
spring:
  application:
    name: rocketmq-all-consumer # 服务名称

rocketmq:
  name-server: 192.168.1.125:9876;192.168.1.126:9876 # NameServer
  producer:
    group: my-group
    retry-times-when-send-failed: 5 # 因时间过时而发送失败消息的重试次数
    retry-times-when-send-async-failed: 2 # 异步消息发送失败重试次数
    max-message-size: 4194304 # 设置一条消息的最大大小，4MB
    send-message-timeout: 3000 # 设置消息发送过期时间
    compress-message-body-threshold: 4096 # 消息大小超过 4k，则被压缩，默认大小4k
    retry-next-server: false # 消息存储失败，是否允许发送换 broker

logging:
  file:
    path: E:/logs/rocketmq-all-consumer.log
  config: # classpath:logback.xml




